services:
  - type: web
    name: clarify-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false